name: Build

on:
  push:
    branches: [ release-*-intel ]
  pull_request:
    branches: [ release-*-intel ]

env:
  HUB: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: self-hosted
    environment:
      name: dev

    env:
      TAG: ${{ github.base_ref || github.ref_name }} 
    steps:
    - uses: actions/checkout@v3

    - name: Build image Proxyv2
      run: |
        ./.github/workflows/build.sh
      env:
        UPDATE_BRANCH: ${{ github.base_ref || github.ref_name }} 

    - name: Login to the container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.HUB }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image Proxyv2
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        docker push ${HUB}/proxyv2:${TAG}
