name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-20.04
    if: github.repository == 'envoyproxy/envoy'
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v3
    - name: 'Dependency Review'
      uses: actions/dependency-review-action@c090f4e553673e6e505ea70d6a95362ee12adb94
