name: mobile_release_validation

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  validate_swiftpm_example:
    name: validate_swiftpm_example
    runs-on: macos-12
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v3
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - run: cd mobile && ./ci/mac_ci_setup.sh
      if: steps.should_run.outputs.run_ci_job == 'true'
      name: 'Install dependencies'
    - name: 'Build xcframework'
      if: steps.should_run.outputs.run_ci_job == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw build \
            --config=ios \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //:ios_xcframework
    # Ignore errors: Bad CRC when unzipping large files: https://bbs.archlinux.org/viewtopic.php?id=153011
    - run: unzip mobile/bazel-bin/library/swift/Envoy.xcframework.zip -d mobile/examples/swift/swiftpm/Packages || true
      if: steps.should_run.outputs.run_ci_job == 'true'
      name: 'Unzip xcframework'
    - run: xcodebuild -project mobile/examples/swift/swiftpm/EnvoySwiftPMExample.xcodeproj -scheme EnvoySwiftPMExample -destination platform="iOS Simulator,name=iPhone 14 Pro Max,OS=16.1"
      if: steps.should_run.outputs.run_ci_job == 'true'
      name: 'Build app'
    # TODO(jpsim): Run app and inspect logs to validate
